/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ApiCsfloatPriceRouteImport } from './routes/api/csfloat-price'
import { Route as ApiMarketcsgoPriceRouteImport } from './routes/api/marketcsgo-price'
import { Route as ApiPricesRouteImport } from './routes/api/prices'
import { Route as ApiSkinportHistoryRouteImport } from './routes/api/skinport-history'
import { Route as ApiSkinportPriceRouteImport } from './routes/api/skinport-price'
import { Route as ApiSteamCallbackRouteImport } from './routes/api/steam-callback'
import { Route as ApiSteamInventoryRouteImport } from './routes/api/steam-inventory'
import { Route as ApiSteamLoginRouteImport } from './routes/api/steam-login'
import { Route as ApiSteamLogoutRouteImport } from './routes/api/steam-logout'
import { Route as ApiSteamPriceRouteImport } from './routes/api/steam-price'
import { Route as ApiSteamProfileRouteImport } from './routes/api/steam-profile'
import { Route as ItemIdRouteImport } from './routes/item.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCsfloatPriceRoute = ApiCsfloatPriceRouteImport.update({
  id: '/api/csfloat-price',
  path: '/api/csfloat-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketcsgoPriceRoute = ApiMarketcsgoPriceRouteImport.update({
  id: '/api/marketcsgo-price',
  path: '/api/marketcsgo-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricesRoute = ApiPricesRouteImport.update({
  id: '/api/prices',
  path: '/api/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkinportHistoryRoute = ApiSkinportHistoryRouteImport.update({
  id: '/api/skinport-history',
  path: '/api/skinport-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkinportPriceRoute = ApiSkinportPriceRouteImport.update({
  id: '/api/skinport-price',
  path: '/api/skinport-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSteamCallbackRoute = ApiSteamCallbackRouteImport.update({
  id: '/api/steam-callback',
  path: '/api/steam-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSteamInventoryRoute = ApiSteamInventoryRouteImport.update({
  id: '/api/steam-inventory',
  path: '/api/steam-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSteamLoginRoute = ApiSteamLoginRouteImport.update({
  id: '/api/steam-login',
  path: '/api/steam-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSteamLogoutRoute = ApiSteamLogoutRouteImport.update({
  id: '/api/steam-logout',
  path: '/api/steam-logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSteamPriceRoute = ApiSteamPriceRouteImport.update({
  id: '/api/steam-price',
  path: '/api/steam-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSteamProfileRoute = ApiSteamProfileRouteImport.update({
  id: '/api/steam-profile',
  path: '/api/steam-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/api/csfloat-price': typeof ApiCsfloatPriceRoute
  '/api/marketcsgo-price': typeof ApiMarketcsgoPriceRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/skinport-history': typeof ApiSkinportHistoryRoute
  '/api/skinport-price': typeof ApiSkinportPriceRoute
  '/api/steam-callback': typeof ApiSteamCallbackRoute
  '/api/steam-inventory': typeof ApiSteamInventoryRoute
  '/api/steam-login': typeof ApiSteamLoginRoute
  '/api/steam-logout': typeof ApiSteamLogoutRoute
  '/api/steam-price': typeof ApiSteamPriceRoute
  '/api/steam-profile': typeof ApiSteamProfileRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/api/csfloat-price': typeof ApiCsfloatPriceRoute
  '/api/marketcsgo-price': typeof ApiMarketcsgoPriceRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/skinport-history': typeof ApiSkinportHistoryRoute
  '/api/skinport-price': typeof ApiSkinportPriceRoute
  '/api/steam-callback': typeof ApiSteamCallbackRoute
  '/api/steam-inventory': typeof ApiSteamInventoryRoute
  '/api/steam-login': typeof ApiSteamLoginRoute
  '/api/steam-logout': typeof ApiSteamLogoutRoute
  '/api/steam-price': typeof ApiSteamPriceRoute
  '/api/steam-profile': typeof ApiSteamProfileRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/api/csfloat-price': typeof ApiCsfloatPriceRoute
  '/api/marketcsgo-price': typeof ApiMarketcsgoPriceRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/skinport-history': typeof ApiSkinportHistoryRoute
  '/api/skinport-price': typeof ApiSkinportPriceRoute
  '/api/steam-callback': typeof ApiSteamCallbackRoute
  '/api/steam-inventory': typeof ApiSteamInventoryRoute
  '/api/steam-login': typeof ApiSteamLoginRoute
  '/api/steam-logout': typeof ApiSteamLogoutRoute
  '/api/steam-price': typeof ApiSteamPriceRoute
  '/api/steam-profile': typeof ApiSteamProfileRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/api/csfloat-price'
    | '/api/marketcsgo-price'
    | '/api/prices'
    | '/api/skinport-history'
    | '/api/skinport-price'
    | '/api/steam-callback'
    | '/api/steam-inventory'
    | '/api/steam-login'
    | '/api/steam-logout'
    | '/api/steam-price'
    | '/api/steam-profile'
    | '/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/api/csfloat-price'
    | '/api/marketcsgo-price'
    | '/api/prices'
    | '/api/skinport-history'
    | '/api/skinport-price'
    | '/api/steam-callback'
    | '/api/steam-inventory'
    | '/api/steam-login'
    | '/api/steam-logout'
    | '/api/steam-price'
    | '/api/steam-profile'
    | '/item/$id'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/api/csfloat-price'
    | '/api/marketcsgo-price'
    | '/api/prices'
    | '/api/skinport-history'
    | '/api/skinport-price'
    | '/api/steam-callback'
    | '/api/steam-inventory'
    | '/api/steam-login'
    | '/api/steam-logout'
    | '/api/steam-price'
    | '/api/steam-profile'
    | '/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  ApiCsfloatPriceRoute: typeof ApiCsfloatPriceRoute
  ApiMarketcsgoPriceRoute: typeof ApiMarketcsgoPriceRoute
  ApiPricesRoute: typeof ApiPricesRoute
  ApiSkinportHistoryRoute: typeof ApiSkinportHistoryRoute
  ApiSkinportPriceRoute: typeof ApiSkinportPriceRoute
  ApiSteamCallbackRoute: typeof ApiSteamCallbackRoute
  ApiSteamInventoryRoute: typeof ApiSteamInventoryRoute
  ApiSteamLoginRoute: typeof ApiSteamLoginRoute
  ApiSteamLogoutRoute: typeof ApiSteamLogoutRoute
  ApiSteamPriceRoute: typeof ApiSteamPriceRoute
  ApiSteamProfileRoute: typeof ApiSteamProfileRoute
  ItemIdRoute: typeof ItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/csfloat-price': {
      id: '/api/csfloat-price'
      path: '/api/csfloat-price'
      fullPath: '/api/csfloat-price'
      preLoaderRoute: typeof ApiCsfloatPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketcsgo-price': {
      id: '/api/marketcsgo-price'
      path: '/api/marketcsgo-price'
      fullPath: '/api/marketcsgo-price'
      preLoaderRoute: typeof ApiMarketcsgoPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prices': {
      id: '/api/prices'
      path: '/api/prices'
      fullPath: '/api/prices'
      preLoaderRoute: typeof ApiPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skinport-history': {
      id: '/api/skinport-history'
      path: '/api/skinport-history'
      fullPath: '/api/skinport-history'
      preLoaderRoute: typeof ApiSkinportHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skinport-price': {
      id: '/api/skinport-price'
      path: '/api/skinport-price'
      fullPath: '/api/skinport-price'
      preLoaderRoute: typeof ApiSkinportPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/steam-callback': {
      id: '/api/steam-callback'
      path: '/api/steam-callback'
      fullPath: '/api/steam-callback'
      preLoaderRoute: typeof ApiSteamCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/steam-inventory': {
      id: '/api/steam-inventory'
      path: '/api/steam-inventory'
      fullPath: '/api/steam-inventory'
      preLoaderRoute: typeof ApiSteamInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/steam-login': {
      id: '/api/steam-login'
      path: '/api/steam-login'
      fullPath: '/api/steam-login'
      preLoaderRoute: typeof ApiSteamLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/steam-logout': {
      id: '/api/steam-logout'
      path: '/api/steam-logout'
      fullPath: '/api/steam-logout'
      preLoaderRoute: typeof ApiSteamLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/steam-price': {
      id: '/api/steam-price'
      path: '/api/steam-price'
      fullPath: '/api/steam-price'
      preLoaderRoute: typeof ApiSteamPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/steam-profile': {
      id: '/api/steam-profile'
      path: '/api/steam-profile'
      fullPath: '/api/steam-profile'
      preLoaderRoute: typeof ApiSteamProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  ApiCsfloatPriceRoute: ApiCsfloatPriceRoute,
  ApiMarketcsgoPriceRoute: ApiMarketcsgoPriceRoute,
  ApiPricesRoute: ApiPricesRoute,
  ApiSkinportHistoryRoute: ApiSkinportHistoryRoute,
  ApiSkinportPriceRoute: ApiSkinportPriceRoute,
  ApiSteamCallbackRoute: ApiSteamCallbackRoute,
  ApiSteamInventoryRoute: ApiSteamInventoryRoute,
  ApiSteamLoginRoute: ApiSteamLoginRoute,
  ApiSteamLogoutRoute: ApiSteamLogoutRoute,
  ApiSteamPriceRoute: ApiSteamPriceRoute,
  ApiSteamProfileRoute: ApiSteamProfileRoute,
  ItemIdRoute: ItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
